config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks
  end
  resources :tasks do
    resources :comments, only: [:new, :create]
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true

    belongs_to :user
    has_many :tasks, dependent: :destroy

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_task_id  (task_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
    belongs_to :task
    belongs_to :user
    validates :content, presence: true
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  introduction :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
    belongs_to :user
    has_one_attached :avatar
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  limit_date  :date
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  board_id    :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
    belongs_to :user
    belongs_to :board
    has_many :comments, dependent: :destroy
    has_one_attached :eyecatch

    validates :name, presence: true
    validates :description, presence: true
    #validates :limit_date, presence: true

    def comment_count
        comments.count
    end
    
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  
  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  def has_written?(board)
    boards.exists?(id: board.id)
  end
  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end

end

app/controllers/Boards_controller.rb
class BoardsController < ApplicationController
    before_action :set_board, only: [:show]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


    def index
        @boards = Board.all
    end

    def show
        @tasks = @board.tasks
        
    end
    def new
        @board = current_user.boards.build
    end
    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to board_path(@board), notice: '保存できたよ'
        else
            flash.now[:error] = '保存に失敗しました'
            render :new
        end
    end
    def edit
        @board = current_user.boards.find(params[:id])
    end
    
    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
            redirect_to board_path(@board), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end
    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end

    
    private
    def board_params
        params.require(:board).permit(:name, :description)
    end

    def set_board
        @board = Board.find(params[:id])
    end
end

app/controllers/Home_controller.rb
class HomeController < ApplicationController
    def index
    @board = Board.first
    end
end

app/controllers/Tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
    end

    def show
        @task = Task.find(params[:id])
        @comments = @task.comments
    end

    def new
        board = Board.find(params[:board_id])
        @task = board.tasks.build
        @task.user = current_user
    end

    def create
        board = Board.find(params[:board_id])
        @task = board.tasks.build(task_params)
        @task.user = current_user
        if @task.save
            redirect_to board_path(board), notice: 'タスクを追加'
        else
            flash.now[:error] = '追加できませんでした'
            render :new
        end
    end

    def edit
        @task = current_user.tasks.find(params[:id])
        
    end

    def update
        task = current_user.tasks.find(params[:id])
        if task.update(task_params)
            redirect_to task_path(task), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end
    def destroy
        task =  current_user.tasks.find(params[:id])
        board = task.board
        task.destroy!
        redirect_to board_path(board), notice: '削除しました。'
    end
    

    
    private
    def task_params
        params.require(:task).permit(:name, :description, :eyecatch)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @task = Task.find(params[:task_id])
        @comment = @task.comments.build
    end

    def create
        task = Task.find(params[:task_id])
        @comment = task.comments.build(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            redirect_to task_path(task), notice: 'コメントを追加'
        else
            flash.now[:error] = '更新できませんでした'
            render :new
        end
    end
    
        private
        def comment_params
        params.require(:comment).permit(:content)
        end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!


    def show
        @profile = current_user.profile
    end

    def edit
        @profile = current_user.prepare_profile
    end
    def update
        @profile = current_user.prepare_profile
        @profile.assign_attributes(profile_params)
        if @profile.save
            redirect_to profile_path, notice: 'プロフィール更新！'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end
    
    private
    def profile_params
        params.require(:profile).permit(:introduction, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.haml
= form_with(model: board, local: true) do |f|
  %div
    = f.label :name, 'Name'
  %div
    = f.text_field :name, class: 'text'
  %div
    = f.label :description, 'Description'
  %div
    = f.text_area :description, class: 'text'
  = f.submit 'Submit', class: 'btn-primary'

app/views/boards/edit.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = render 'form', board: @board

app/views/boards/index.html.haml
.container
  %h1 All Boards
  - @boards.each do |board|
    
    .card
      .card_content
        .card_title.flex
          = board.name
          - if user_signed_in? && current_user.has_written?(board)
            .dropdown
              = image_tag 'Combined Shape', class: 'dropbtn'
              .dropdown-content.mini
                = link_to 'Edit', edit_board_path(board)
                = link_to 'Delete', board_path(board), data: { method: 'delete', confirm: '本当に削除してもいいですか？'} 
        = link_to board_path(board) do
          = board.description
          .card_detail
            = image_tag board.user.avatar_image
  = link_to new_board_path do
    .new_btn
      %p.i + Add new board

app/views/boards/new.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  %h1 New Boards
  = render 'form', board: @board

app/views/boards/show.html.haml
.container
  .board_title
    = @board.name
  - @tasks.each do |task|
    = link_to task_path(task) do
      .board
        - if task.eyecatch.attached?
          .board_image
            = image_tag task.eyecatch
        .board_content
          .task_title
            = task.name
            = image_tag 'Combined Shape', class: 'dropbtn'
          = task.description
          .board_detail
            = image_tag task.user.avatar_image
            .board_comment
              = image_tag 'comment.svg'
              %span= task.comment_count

  = link_to new_board_task_path(@board) do
    .board_add.new_btn
      +Add new card
  = link_to root_path do
    .btn-primary
      %p Topに戻る

app/views/comments/new.html.haml
.container
    %h2.header_new New Comment
    %ul
        - @comment.errors.full_messages.each do |message|
            %li= message

    = form_with(model: @comment, url: task_comments_path(@comment.task), local: true) do |f|

        %div
            = f.text_area :content
        = f.submit '保存', class: 'btn-primary'

app/views/home/index.html.erb
<h1>All Boards</h1>
<h2><%= @board.name %></h2>
<h2><%= @board.description %></h2>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AyanoTodo
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.header
      %p.header_pageTitle Boards
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'プロフィール', profile_path
            = link_to 'logout', destroy_user_session_path,data: { method: 'delete' }
            = link_to 'top', root_path
      - else
        = link_to 'login', new_user_session_path, class: 'header_loginBtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.container
    %ul
    - @profile.errors.full_messages.each do |message|
        %li= message

    = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
        %div
            = f.label :avatar, 'アバター'
        %div
            = f.file_field :avatar
        %div
            = f.label :introduction, '自己紹介'
        %div
            = f.text_area :introduction
        = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
    .profilePage_user
        .profilePage_user_image
            = image_tag current_user.avatar_image
        .profilePage_user_basicInfo
            .profilePage_user_actionButton
                = link_to 'Edit', edit_profile_path
            .profilePage_user_introduction
                = current_user.profile&.introduction

app/views/tasks/edit.html.haml
.container
    %ul
    - @task.errors.full_messages.each do |message|
        %li= message
    %h1 New Card
    = form_with(model: @task, url: board_tasks_path(@task.board),method: 'post', local: true) do |f|
        %div
            = f.file_field :eyecatch
        %div
            = f.label :name, 'Name'
        %div
            = f.text_field :name, class: 'text'
        %div
            = f.label :description, 'Description'
        %div
            = f.text_area :description, class: 'text'
        = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/new.html.haml
.container
    %ul
    - @task.errors.full_messages.each do |message|
        %li= message
    %h1 New Card
    = form_with(model: @task, url: board_tasks_path(@task.board),method: 'post', local: true) do |f|
        %div
            = f.file_field :eyecatch
        %div
            = f.label :name, 'Name'
        %div
            = f.text_field :name, class: 'text'
        %div
            = f.label :description, 'Description'
        %div
            = f.text_area :description, class: 'text'
        = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/show.html.haml
.container 
    .task_title
        = @task.name
        
        .task_detail_actions
        .dropdown
            = image_tag 'Combined Shape.svg', class: 'dropbtn'
            .dropdown-content.mini
                = link_to 'Edit', edit_board_task_path(@task)
                = link_to 'Delete', board_task_path(@task), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
    - if @task.eyecatch.attached?
        .task_image
            = image_tag @task.eyecatch
    .task
        .task_detail
            .task_content
                = @task.description
    

    .comment_title
        Comment
    
    - @comments.each do |comment|
        .comment
            .comment_detail
                = image_tag comment.user.avatar_image
                %p= comment.content

    .comment_add.new_btn
        = link_to new_task_comment_path(@task) do
            +Add new comment
    